services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elastic

  suggester:
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
    build: './'
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    command: python3 /app/main.py elasticsearch && python3 /app/setup.py elasticsearch


networks:
  elastic:
    driver: bridge